use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct Quote {
    pub symbol: String,
    pub name: String,
    pub price: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pre_market_price: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub after_hours_price: Option<String>,
    pub change: String,
    pub percent_change: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub open: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub high: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub low: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub year_high: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub year_low: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub volume: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub avg_volume: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub market_cap: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub beta: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pe: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub eps: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dividend: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dividend_yield: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ex_dividend: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub net_assets: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub nav: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expense_ratio: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_capital_gain: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub morningstar_rating: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub morningstar_risk_rating: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub holdings_turnover: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub earnings_date: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_dividend: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inception_date: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sector: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub industry: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub about: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub employees: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub five_days_return: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub one_month_return: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub three_month_return: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub six_month_return: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ytd_return: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub year_return: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub three_year_return: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub five_year_return: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ten_year_return: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_return: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logo: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct SimpleQuote {
    pub symbol: String,
    pub name: String,
    pub price: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pre_market_price: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub after_hours_price: Option<String>,
    pub change: String,
    pub percent_change: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logo: Option<String>,
}

